mysite/brs/urls.py
from django.urls import path
from . import views

app_name = 'brs'

urlpatterns = [
    # post views
    path('', views.main, name='main'),
    path('booking/', views.booking, name='booking'),
    path('cancellation/', views.cancellation, name='cancellation'),
    path('status/', views.status, name='status'),
    path('tickets/<slug:slug>', views.ticket_detail, name='ticket_detail'),
    path('tickets/delete/<int:number>', views.delete_ticket, name='delete_ticket'),
    path('tickets/search/', views.search_ticket, name='search_ticket'),
    path('buses/', views.bus_list, name='bus_list'),
    path('buses/<slug:slug>/',
         views.bus_detail,
         name='bus_detail'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('brs/', include('brs.urls', namespace='brs')),
]

mysite/brs/models.py
from enum import auto
from pyexpat import model
from statistics import mode
from tabnanny import verbose
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
import uuid

class Bus(models.Model):
    STATUS_CHOICES = (('available', 'Available'), ('not_available', 'Not Available'),)
    title = models.CharField(max_length=250)
    number = models.CharField(max_length=4, unique=True)
    slug = models.SlugField(max_length=256, unique=True)
    departure_time = models.DateTimeField()
    destination = models.CharField(max_length=250)
    available_seats = models.PositiveIntegerField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=15, choices=STATUS_CHOICES, default='available')
    class Meta:
        ordering = ('-available_seats',)
        verbose_name = 'Bus'
        verbose_name_plural = 'Buses'
    def __str__(self):
        return self.title + " - " + self.number
    def get_absolute_url(self):
        return reverse('brs:bus_detail', args=[self.slug])

class Ticket(models.Model):
    name = models.CharField(max_length=250)
    number = models.AutoField(primary_key=True)
    slug = models.SlugField(max_length=512, unique=True)
    bus = models.ForeignKey(Bus,
                            on_delete=models.CASCADE,
                            related_name='tickets')
    booked_seats = models.PositiveIntegerField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    unit_price = models.DecimalField(max_digits=19, decimal_places=2, default=5.00)
    def __str__(self):
        return self.name + " - " + str(self.number)
    def get_absolute_url(self):
        return reverse('brs:ticket_detail', args=[self.slug])

mysite/brs/forms.py
from django import forms
from .models import Ticket, Bus

class TicketForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = ('name', 'bus', 'booked_seats')

class SearchForm(forms.Form):
    query = forms.CharField()

mysite/brs/views.py
from datetime import datetime
import imp
from django.http import HttpResponseRedirect
from time import timezone
from xmlrpc.client import DateTime
from django.shortcuts import render, get_object_or_404
from .models import Bus, Ticket
from .forms import TicketForm, SearchForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from datetime import datetime
from django.shortcuts import redirect
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.
def main(request):
    return render(request, 'brs/main.html', {})

def booking(request):
    new_ticket = None
    error = ''
    if request.method == 'POST':
        ticket_form = TicketForm(data=request.POST)
        if ticket_form.is_valid():
            new_ticket = ticket_form.save(commit=False)
            bus = ticket_form.cleaned_data['bus']
            if new_ticket.booked_seats == 0:
                error = 'You can not book 0 seats'
                return render(request, 'brs/booking.html', {'ticket_form': ticket_form, 'error': error})
            if bus.available_seats < new_ticket.booked_seats:
                error = 'This many seats are not available.'
                return render(request, 'brs/booking.html', {'ticket_form': ticket_form, 'error': error})
            bus.available_seats -= new_ticket.booked_seats
            if bus.available_seats == 0:
                bus.status = 'not_available'
            bus.save()
            name = ticket_form.cleaned_data['name'].replace(' ', '-').lower()
            ticket_date = str(datetime.now().strftime("%Y-%m-%d-%H-%M-%S"))
            new_ticket.slug = name + "-" + ticket_date
            new_ticket.save()
            return HttpResponseRedirect(new_ticket.get_absolute_url())
    else:
        ticket_form = TicketForm()
    return render(request, 'brs/booking.html', {'ticket_form': ticket_form, 'error': error})

def cancellation(request):
    return render(request, 'brs/cancellation.html', {})

def status(request):
    return render(request, 'brs/status.html', {})

def bus_list(request):
    object_list = Bus.objects.all()
    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')
    try:
        buses = paginator.page(page)
    except PageNotAnInteger:
        buses = paginator.page(1)
    except EmptyPage:
        buses = paginator.page(paginator.num_pages)
    return render(request, 'brs/bus/list.html', {'page': page, 'buses': buses})

def bus_detail(request, slug):
    bus = get_object_or_404(Bus, slug=slug)
    return render(request, 'brs/bus/detail.html', {'bus': bus})

def ticket_detail(request, slug):
    ticket = get_object_or_404(Ticket, slug=slug)
    return render(request, 'brs/ticket/detail.html', {'ticket': ticket})

def delete_ticket(request, number):
    ticket = get_object_or_404(Ticket, number=number)
    bus = ticket.bus
    bus.available_seats += ticket.booked_seats
    bus.save()
    ticket.delete()
    return redirect('/brs/booking/')

def search_ticket(request):
    form = SearchForm()
    query = None
    ticket = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            try:
                ticket = Ticket.objects.get(number=query)
            except ObjectDoesNotExist:
                ticket = []
    return render(request,
                  'brs/ticket/search.html',
                  {'form': form,
                   'query': query,
                   'ticket': ticket})

mysite/brs/templates/brs/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static " css/blog.css" %}" rel="stylesheet">
</head>

<body>
    <h1><a href="{% url 'brs:main' %}">Bus Registration System</a></h1>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
</body>

</html>

mysite/brs/templates/brs/booked.html
{% extends "brs/base.html" %}
{% block title %}{{ ticket.name }}{% endblock %}
{% block content %}
<h1>{{ ticket.name }} - {{ ticket.number }}</h1>
<h3>{{ ticket.bus.title }} - {{ ticket.bus.number }}</h3>
<h5>Status: {{ ticket.bus.status }}</h5>
<p>
    Leaving for {{ ticket.bus.destination }} by {{ ticket.bus.departure_time }}
</p>
<p>Booked {{ ticket.booked_seats }} seat{{ ticket.booked_seats|pluralize }}.</p>
<a href="{% url 'brs:booking' %}">Need another ticket?</a>
{% endblock %}

mysite/brs/templates/brs/booking.html
{% extends "brs/base.html" %}
{% block title %}Book Ticket{% endblock %}
{% block content %}
<h1>Get your ticket!</h1>
<form method="post">
    {{ ticket_form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Book"></p>
</form>
<p>{{ error }}</p>
{% endblock %}

mysite/brs/templates/brs/bus/detail.html
{% extends "brs/base.html" %}
{% block title %}{{ bus.title }}{% endblock %}
{% block content %}
<h1>{{ bus.title }} - {{ bus.number }}</h1>
<h5>Status: {{ bus.status }}</h5>
<p>
    Leaving for {{ bus.destination }} by {{ bus.departure_time }}
</p>
<p>Seats available: {{ bus.available_seats }}</p>
{% endblock %}

mysite/brs/templates/brs/bus/list.html
{% extends "brs/base.html" %}
{% block title %}Buses{% endblock %}
{% block content %}
<h1>Buses</h1>
{% for bus in buses %}
<h2>
    <a href="{{ bus.get_absolute_url }}">
        {{ bus.title }} - {{ bus.number }}
    </a>
</h2>
<p class="date">
    Leaving for {{ bus.destination }} by {{ bus.departure_time }}
</p>
{% endfor %}
{% include "pagination.html" with page=buses %}
{% endblock %}

mysite/brs/templates/brs/main.html
{% extends "brs/base.html" %}
{% block title %}Bus Registration System{% endblock %}
{% block content %}
<h1>Bus Registration System</h1>
<p><a href="{% url 'brs:bus_list' %}"><input type="submit" value="Buses List"></a></p>
<p><a href="{% url 'brs:booking' %}"><input type="submit" value="Buy Ticket"></a></p>
<p><a href="{% url 'brs:search_ticket' %}"><input type="submit" value="Check Ticket"></a></p>
{% endblock %}

mysite/brs/templates/brs/ticket/detail.html
{% extends "brs/base.html" %}
{% block title %}{{ ticket.name }}{% endblock %}
{% block content %}
<h1>{{ ticket.name }} - {{ ticket.number }}</h1>
<h3>{{ ticket.bus.title }} - {{ ticket.bus.number }}</h3>
<h4>Ticket Number: {{ ticket.number }}</h4>
<h5>Status: {{ ticket.bus.status }}</h5>
<p>
    Leaving for {{ ticket.bus.destination }} by {{ ticket.bus.departure_time }}
</p>
<p>Booked {{ ticket.booked_seats }} seat{{ ticket.booked_seats|pluralize }}.</p>
<p><a href="{% url 'brs:booking' %}">Need another ticket?</a></p>
<p><a href="{% url 'brs:delete_ticket' number=ticket.number %}"><input type="submit" value="Delete"></a></p>
{% endblock %}

mysite/brs/templates/brs/ticket/search.html
{% extends "brs/base.html" %}
{% block title %}Search{% endblock %}
{% block content %}<h1>Search for tickets</h1>
<form method="get">
    {{ form.as_p }}
    <input type="submit" value="Search">
</form>
{% if query %}
    {% if ticket %}
        <h1>Search results for "{{ query }}"</h1>
        <h3>Name: <a href="{{ ticket.get_absolute_url }}">{{ ticket.name }}</a></h4>
        <h4>Number: <a href="{{ ticket.get_absolute_url }}">{{ ticket.number }}</a></h4>
        <h5>Bus: <a href="{{ ticket.get_absolute_url }}">{{ ticket.bus.title }}</a></h4>
    {% else %}
        <h1>Ticket for ticket number "{{ query }}" does not exist</h1>
    {% endif %}
{% endif %}
{% endblock %}

mysite/brs/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>